# Generated by Django 3.0.7 on 2020-07-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('job_title', models.CharField(choices=[('MG', 'Менеджер'), ('AD', 'Администратор'), ('ST', 'Персонал')], max_length=2)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('works_for', models.CharField(help_text='Введите название вашего объекта размещения.', max_length=100)),
                ('property_id', models.CharField(help_text='Введите 32-ти значную последовательность цифр и букв. Храните её в секрете, она служит для защиты', max_length=48)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
