# Generated by Django 3.0.7 on 2020-07-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='property_id',
            field=models.CharField(max_length=88),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='property_id',
            field=models.CharField(max_length=88),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='property_id',
            field=models.CharField(max_length=88),
        ),
        migrations.AlterField(
            model_name='room',
            name='property_id',
            field=models.CharField(max_length=88),
        ),
    ]
