# Generated by Django 2.2 on 2020-05-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200523_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='checkout_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, choices=[('DT', 'Грязная'), ('CL', 'Чистая'), ('DnD', 'Не беспокоить'), ('MiR', 'Горничная в номере')], max_length=3, null=True),
        ),
    ]
