# Generated by Django 2.2 on 2020-05-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200525_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='checkout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
