# Generated by Django 3.0.7 on 2020-06-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200525_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, choices=[('Грязная', 'Грязная'), ('Чистая', 'Чистая'), ('Не беспокоить', 'Не беспокоить'), ('Горничная в номере', 'Горничная в номере')], max_length=18, null=True),
        ),
    ]
