# Generated by Django 3.0.7 on 2020-06-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200622_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
