# Generated by Django 3.0.7 on 2020-06-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200624_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cleaning_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='dashboard.Cleaning'),
        ),
    ]
